### ISSUE TITLE
Ingenuity Neighbors

### ISSUE THREAD

**Issue by Cwighty** [SnowSE/mars_rover#11]
https://github.com/SnowSE/mars_rover/blob/61c5be8ef3b1bbc58d5b7291b1f79f9a34145129/src/Mars.MissionControl/Game.cs#L177

I noticed my neighbors were never changing for my ingenuity rover. I think I tracked it down to this line of code. Shouldn't it be passing the ingenuity location not the perseverance location?

**Comment by snow-jallen** [comment]
you're absolutely correct.  fixed
